debug = true
salt = "111165de3c3adfb9dc4a79d1ca701111"
intervalForUpdateValidStatus = 10 
jobTimeoutHours = 8

[server]
listen = ":80"

[service_url]
clientSvcUrl = "http://jcloud-cs-svc:9000" # 客户中心地址
basicSvcUrl = "http://jcloud-bs-svc:8090" # 基础服务地址
basicSvcRpcUrl = "jcloud-bs-svc:8091" # 基础服务rpc地址
messageSvcUrl = "jcloud-message-svc:8900" # 消息中心地址
billSvcUrl = "http://34.234.3.62:7890"  # 账单后台地址

[mongo]
addr = "mongodb://mongo1:27017"
user = "jcloud_fs"
pass = "QvXgna47Tsx6HcYodjPFXg=="
dbname = "jcloud-fs"
fsdbname = "jscloud-fs-files"

[secretkey]
aws=""
awscn=""

