# 服务基础配置
debug = true
salt = "111165de3c3adfb9dc4a79d1ca701111"

# 服务http配置
[server]
listen = ":9000"

# 数据库配置
[mysql]
debug = true
idle = 10
max = 20
maxopenconn = 10
addr = "@tcp(mysql-svc:3306)/mc_customer?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
user = "root"
pass = "QvXgna47Tsx6HcYodjPFXg=="

# 外部链接服务配置
[services]
basicrpc = "jcloud-bs-svc:8081"
billing = "http://jcloud-fs-svc:8527"
