debug = true
baseUrl = "http://opsphere.cloud"

[server]
listen = ":8999"

[mysql]
user = "root"
pass = "abcd.1234"
addr = "@tcp(mysql-svc:3306)/jcloud_ts?charset=utf8&&loc=Asia%2FShanghai&parseTime=true"
debug = true
idle = 10
max = 20
maxopenconn = 10

[services]
basic = "http://jcloud-bs-svc:8090"
message = "http://jcloud-message-svc:8900"

